# Generated by Django 4.2 on 2023-05-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_criador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='carga_horario',
            new_name='carga_horaria',
        ),
    ]
