# Generated by Django 4.2 on 2023-05-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_carga_horario_event_carga_horaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cor_segundaria',
            new_name='cor_secundaria',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='username',
            new_name='nome',
        ),
    ]
